package application.samples.dialogs.textAreaDialog;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

public class TextAreaDialogController {
	@FXML
	private Label contentText;
	@FXML
	private TextArea textArea;
	@FXML
	private Button modifyButton;
	@FXML
	private Button cancelButton;

	// Event Listener on Button[#modifyButton].onAction
	@FXML
	public void modifyText(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancelAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
