package application.samples.bookPage;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import data.Book;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

/**
 * Controller for displaying a book informations's window.<p>
 * To display this, you need to load the FXML resource, and then call {@link bookPageController#initData(Book)} in order to make it work.
 * @author Aldric Vitali Silvestre
 * @see bookPageController#initData(Book)
 */
public class bookPageController implements Initializable{
	/*=======Page components=======*/
	@FXML
	private Button modifyDescriptionButton;
	@FXML
	private TextArea descriptionTextArea;
	@FXML
	private Button modifyKeywordsButton;
	@FXML
	private TextArea keywordsTextArea;
	@FXML
	private Label titleLabel;
	@FXML
	private Button modifyTitleButton;
	@FXML
	private Label authorLabel;
	@FXML
	private Button modifyAuthorButton;
	@FXML
	private Label categoryLabel;
	@FXML
	private Button modifyCategoryButton;
	@FXML
	private Button saveModificationsButton;
	@FXML
	private Button deleteBookButton;
	@FXML
	private Label borrowLabel;
	@FXML
	private Button modifyBorrowButton;
	
	/*=======Attributes=======*/
	private Book book;
	private boolean isBookBorrowed;

	/*=======Initialization=======*/
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * Init all needed data in window from a specified book.<p>
	 * This method needs to be called before showing th stage.
	 * @param book the book we want to display data
	 */
	public void initData(Book book) {
		this.book = book;
	}
	
	/*=======Listeners methods=======*/
	// Event Listener on Button[#modifyDescriptionButton].onAction
	@FXML
	public void modifyDescription(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modifyKeywordsButton].onAction
	@FXML
	public void modifyKeywords(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modifyTitleButton].onAction
	@FXML
	public void modifyTitle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modifyAuthorButton].onAction
	@FXML
	public void modifyAuthor(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modifyCategoryButton].onAction
	@FXML
	public void modifyCategory(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#saveModificationsButton].onAction
	@FXML
	public void saveModifications(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteBookButton].onAction
	@FXML
	public void deleteBook(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modifyBorrowButton].onAction
	@FXML
	public void modifyBorrow(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
